spring: 
  application: 
    name: user-service
  data: 
    mongodb: 
      host: localhost
      port: 27017
      database: local
server:
  port: 8181
  host: localhost
  
eureka: 
  client: 
    serviceUrl:
      defaultZone: http://localhost:6677/eureka/
    healthcheck:
      enable: true
  instance: 
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2